[package]
name = "iproc"
description ="A Commandline tool for image processing"
version = "0.1.0"
edition = "2024"
authors = ["Juan Milkah <juanmilkah@gmail.com"]
license = "GNU/GPL-3"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
image = "0.25.5"
